# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ece7cc06239cbe658491e3a2b3370e0495c5efa5caba5e385c588c89688713b560ea8e4df52471afd0587ac6611aa29a4863db43beee5f038b2c10d2ea8ae344

test:
  secret_key_base: 3201311f0ee8ea644dc7f41a373387f67e2001c47bc31170b84c561e7cf6eb876e34aac626dbb9c45451672073e176aa40b3d653a6d239b8c960837dd39d6857

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
